// Generated by CoffeeScript 1.10.0
var MisCursosCtrl, MisCursosDocenteCalendarioCtrl, MisCursosListaCtrl;

MisCursosCtrl = function($scope, $state, $stateParams, $translate) {
  $scope.translate = $translate;
  $scope.errorAniosEscolares = false;
  $scope.dataSelected = {};
  return $scope.go = function(state, obj) {
    if (obj == null) {
      obj = null;
    }
    return $state.go(state, obj);
  };
};

MisCursosListaCtrl = function($scope, $state, $stateParams, spinner, Cursos, Periodos, Tutorial) {
  var loadCursos;
  Periodos.get(function(r) {
    var k, ref, v;
    $scope.anios = r.data.anios;
    if ((Object.keys(r.data.anios).length)) {
      $scope.displayAniosEscolares = true;
      $scope.AnioOptions = [];
      ref = r.data.anios;
      for (k in ref) {
        v = ref[k];
        $scope.AnioOptions.push({
          name: v.ano_escolar,
          value: v.id
        });
      }
      if ($stateParams.anoEscolar) {
        $scope.dataSelected.id_ano_escolar = String($stateParams.anoEscolar);
      } else {
        $scope.dataSelected.id_ano_escolar = $scope.AnioOptions[0].value;
      }
      loadCursos();
      $scope.Tutorial = Tutorial;
      return Tutorial.inicialize("TutorialMisCursos");
    } else {
      spinner.stop("loadCursos");
      return $scope.errorAniosEscolares = true;
    }
  });
  loadCursos = function() {
    $scope.displayCursos = false;
    $scope.errorCursos = false;
    return Cursos.get({
      anio: $scope.dataSelected.id_ano_escolar
    }, function(r) {
      spinner.stop("loadCursos");
      if ((Object.keys(r.data).length)) {
        $scope.displayCursos = true;
        return $scope.cursos = r.data;
      } else {
        return $scope.errorCursos = true;
      }
    });
  };
  return $scope.changeAnioEscolar = function() {
    return loadCursos();
  };
};

MisCursosDocenteCalendarioCtrl = function($scope, $state, $stateParams) {
  return $scope.$parent.anoEscolar = $stateParams.anoEscolar;
};
